language: ruby
rvm:
- 2.2.3
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
deploy:
  provider: heroku
  app:
    master: name-of-your-heroku-instance
  api_key:
    secure: D/MLiK1HUoxGNQ+J1AUTGvWPLhULHu7WBwEIi03qfMVJsIIset3Obnt9LXvGRLd+7huuEbCPPDEI/AToEwiT3MR+R5JHPCHKLK3Ckzmrwa7+K5D8gZiDzrBqCPbt4Sgpx069OfWpXAiyZ6yT1dgCpW9rBvuEwfadTF32nDN3nDfUxkHuafwXB7KzX9ptIuisc+jrqkftxONVBcZeHCpQo7zSfFe+OUUos7gWvHdL6VMA+eziSFmEgrdfylXA4u/pmcAu2pvawXthJI77KJtMjSQQQc/1CMHlf5h6ANNbiSkolMEKGVoyn25lwB+hcpuPCd3GrMC+O3TFhWlMo8Ze8fQ6MW2dS/rbz1tZu/LKcpPAmmLrvwsd870B56uHcCem2aChG7IG0NQwVJYRE9NklxMgl/bJ/p4r/z/D29xi3KZUKLd8DmVLVh8mIexQ239AOF7B6qZ8DyckeIi+omlj2LLwsh2R8nNNUwchNELB4WLPKnUskai1AvdByIiamWV2fn5tMWbPVY293IgtFoIp07zPCWoaJzFydamAsC53D6R5VMuVpbYJT/lu7ZKLNeIPK2H1nxGre99YUcVh+3OLM/eNiGRtgXsRBlYp7S7EFdaZsp6U44A1LdosTQPuuV8uxI8iCSCGediqLrKQYoRqdOuA0XexGhi/2Vt1nbysugM=

sudo: required
